### ISSUE TITLE
Syntax-highlight comments in verso code

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/verso#274]
It would be great if a dedicate `span` tag was placed around `--` and `/-` comments within a lean code snippet.

In https://storage.googleapis.com/deepmind-media/DeepMind.com/Blog/imo-2024-solutions/P2/index.html, I hacked around this with
```css
            .hl.lean {
                color: #c92786
            }

            .hl.lean > * {
                color: black
            }
```

This might also align with future work to exploring rendering markdown and latex inside comments.
